# Generated by Django 5.2 on 2025-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_asda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update_time',
            new_name='update_date',
        ),
    ]
