# Generated by Django 5.2 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_update_time_project_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('asd', 'Python'), ('javascript', 'Javascript'), ('java', 'Java'), ('c', 'C'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('go', 'Go'), ('html', 'HTML'), ('css', 'CSS')], max_length=20),
        ),
    ]
