# Generated by Django 5.2 on 2025-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('Python', 'python'), ('JavaScript', 'js'), ('Java', 'java'), ('C', 'c'), ('C#', 'csharp'), ('Ruby', 'ruby'), ('Go', 'go'), ('HTML', 'html'), ('CSS', 'css')], max_length=20),
        ),
    ]
